### ISSUE TITLE
miss libva.so.2 and libva-xxx.so.2 when using meson build system

### ISSUE THREAD

**Issue by xhaihao** [intel/libva#181]
The application linked with the libraries built by autoconf build system can't run.

`vainfo: error while loading shared libraries: libva-x11.so.2: cannot open shared object file: No such file or directory`

**Comment by ceyusa** [comment]
Where did you install libva? which path?

Can you post the output of $ ldd ./vainfo ??

Perhaps the linker is expecting the libraries in another path.

**Comment by ceyusa** [comment]
an workaround could be to set LD_LIBRARY_PATH to the directory where the libva library is installed

**Comment by xhaihao** [comment]
I forgot I changed some version number in meson.build.

There isn't libva.so.2 if you change the VA-API version to 1.1 and library version to 2.1.0.1, however autotools can create libva.so.2 if I do the same thing in configure.ac.  I thought I can get the same result for meson and autotools if I change the version number only.
