### ISSUE TITLE
Why H264 Encoder is slower than H265 Encoder?

### ISSUE THREAD

**Issue by qiushics** [intel/libva#184]
OS: Ubuntu 16.04 64bit
CPU: intel i7 6700

H264:
ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -i a.h264 -c:v h264_vaapi -f h264 t.h264 -y

108fps

H265:
ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -i a.h265 -c:v hevc_vaapi -f hevc t.h265 -y

126fps

Any ideas?

**Comment by XinfengZhang** [comment]
on SKL, H264 encoder should be faster than h265 encoder, what I mentioned is GPU capabilities, not include software middle ware stack.

**Comment by XinfengZhang** [comment]
sorry, mistakes, what's the related driver?

**Comment by qiushics** [comment]
@XinfengZhang 

VAAPI Driver | CPU |Encoder| FPS
------------ | ------------- | ------------- | -------------
1.7.0| i7 4770| H264| 250fps
1.7.0| i7 6700| H264| 108fps
1.7.0 |i7 6700| H265| 126fps
2.1.1.pre1| i7 6700| H264| 200fps
2.1.1.pre1 |i7 6700| H265| 64fps

**Comment by qiushics** [comment]
I change the driver version, H264 encode performance increase (i7 6700 still slower than i7 4770), but h265 encode performance decrease.

**Comment by xhaihao** [comment]
@qiushics  some new media kernels are used for quality improvement since 1.8.0. it is possible to have some impact to performance. You may give a try with setting quality level to 7, the default quality level is 4.

**Comment by xhaihao** [comment]
@qiushics  BTW this is vaapi driver related, please file your issue to https://github.com/intel/intel-vaapi-driver.

**Comment by qiushics** [comment]
@xhaihao I changed the quality, but skylake still slower than haswell. 
Maybe the vaapi driver problem

**Comment by xhaihao** [comment]
move to https://github.com/intel/intel-vaapi-driver/issues/354
