### ISSUE TITLE
Bump up minor version for 1.2.1

### ISSUE THREAD

**Issue by dvrogozh** [intel/libva#240]
https://github.com/intel/libva/blob/250b3dc8f370bc6d85be767c9722fd98e8b02ebb/configure.ac#L31

Minor version is still on 0 while we are marching towards a 1.2.1 release with 2.2.1.pre1 tags. Please, bump up minor version.

**Comment by dvrogozh** [comment]
@XinfengZhang : do we have a plan to resolve this?

**Comment by XinfengZhang** [comment]
@dvrogozh vaapi version is different with libva version. libva 2.2.x can be a implementation of vaapi 1.2.0

**Comment by uartie** [comment]
Can this be closed?

**Comment by XinfengZhang** [comment]
yes,
