### ISSUE TITLE
Provide release tarballs for 2.3.0

### ISSUE THREAD

**Issue by JoshStrobl** [intel/libva#242]
Please update the releases page with release tarballs for 2.3.0. While minor, xz'ed compressed tarballs and not having to run autogen (rather being able to directly run configure) is quite nice.

**Comment by XinfengZhang** [comment]
thanks, done, please help to check. https://github.com/intel/libva/releases/tag/2.3.0

**Comment by JoshStrobl** [comment]
Can confirm that the tarball produces a successful build. [We've switched back to using it as a downstream.](https://dev.getsol.us/R1886:9811647e402740707bc39250d4a805ea92be2e9c) Thanks again.
