### ISSUE TITLE
driver auto-detection doesn't work for iHD under X11

### ISSUE THREAD

**Issue by grmat** [intel/libva#244]
Quoting from 9f2a994643001a03e103aa13268abbd86b49a5c4:

> Sometimes there exist multiple backend vaapi drivers on one system. In such case user hopes to load the specific driver based on the request. Currently it can be specified by using LIBVA_DRIVER_NAME environment. But it is not convenient.

On a system where iHD va-api driver is installed and i965 is not, any va app will crash with `unknown libva error`. It works correctly when the `LIBVA_DRIVER_NAME` is set to `iHD` manually.

First guess was the lookup in `driver_name_map` (va/drm/va_drm_utils.c), but it will actually use `va-DRI2GetDriverName` and end up with `i965` from there instead of `iHD`.

Under wayland, the according wayland_drm code path is used and the detection works when the drm driver mapping is changed.

**Comment by ramcq** [comment]
I don't believe this patch is sufficient to claim that auto-detection is implemented. When libva is upgraded, it will cause any system that was working with the i965 VA driver to stop working unless the iHD driver is installed. It will also cause any older system, supported by i965 VA driver, and not iHD driver, never to work again. The desired behaviour is clearly that libva would probe whether it can be initialised with one driver (that it's available, and also compatible with the hardware) and if not, fall back to the next one. I think this ticket should be re-opened.

**Comment by XinfengZhang** [comment]
@ramcq , actually it should combined with #351 , if there are no iHD, then it will load i965. please help to check whether #351 meet your requirement. thanks

**Comment by jbeich** [comment]
#351 didn't touch va/x11, so auto-detection only works on console and Wayland.

**Comment by jbeich** [comment]
Nevermind, va/x11 appears to inherit `i965` from DRI2 driver name.
