### ISSUE TITLE
vaCreateContext() doesn't need |render_targets| nor |num_render_targets| parameters

### ISSUE THREAD

**Issue by yellowdoge** [intel/libva#251]
According to this [email thread](https://lists.01.org/pipermail/intel-vaapi-media/2017-July/000052.html), [`vaCreateContext()`](https://github.com/intel/libva/blob/master/va/va.h#L1450) doesn't need the `render_targets` nor `num_render_targets` parameters: consider removing them or adding an overloaded function or a numbered `vaCreateContext2()` method without those.

@rosetta-jpn

**Comment by XinfengZhang** [comment]
@yellowdoge , you can use render_targets to register ref/recon surface , you also can set the render_targets to be nullptr and num_render_targets to 0. I dont understand why we need to remove it. 
another concern is , if you want to use one surface as reference, you should ensure that it is decoded/encoded. so actually it is combined. one surface can be combined with 2 or more contexts. but in one context, when it is used as reference, it must be decoded/encoded in this context.

**Comment by uartie** [comment]
@yellowdoge if @XinfengZhang reply does not satisfy your question, feel free to reopen.

**Comment by linjiling** [comment]
so how do i combine one surface with one context if num_render_targets is zero ?
