### ISSUE TITLE
i915/kbl: vcs0 hang with HEVC 2160p video

### ISSUE THREAD

**Issue by mlauss** [intel/libva#255]
Hello,

Current git-head of libva/libva-intel-driver causes a gpu hang with a 2160p HEVC video:

[   61.008330] [drm] GPU HANG: ecode 9:2:0xa8dfbffd, in VideoPlayer [770], reason: hang on vcs0, action: reset

Attached is the gpu crash dump.
[kblcrash.txt](https://github.com/intel/libva/files/2643984/kblcrash.txt)

**Comment by xhaihao** [comment]
it is an issue in the backend driver, see https://github.com/intel/intel-vaapi-driver/issues/425
