### ISSUE TITLE
FFmpeg MPEG-2 encode fails to "invalid RC mode" when using VA-API

### ISSUE THREAD

**Issue by eero-t** [intel/libva#262]
Setup:
* Ubuntu 18.04
* Any HW with MPEG-2 HW acceleration support enabled by intel-driver
* Latest FFmpeg, MediaSDK, libva, intel-driver and gmmlib built from git
* drm-git kernel v4.19 or v4.20-rc

Test-case:
* FFmpeg MPEG-2 encoding with VA-API:
`ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i 720x480p_30.00_4mb_h264_cabac.264 -c:v mpeg2_vaapi -b:v 2M -compression_level 4 -y output.mpg
`

Actual outcome:
```
Input #0, h264, from '720x480p_30.00_4mb_h264_cabac.264':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(tv, smpte170m, progressive), 720x480 [SAR 10:11 DAR 15:11], 30 fps, 30 tbr, 1200k tbn, 60 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg2video (mpeg2_vaapi))
Press [q] to stop, [?] for help
[mpeg2_vaapi @ 0x564a286e6100] Driver does not support some wanted packed headers (wanted 0x3, found 0x10).
Assertion 0 && "Invalid RC mode." failed at src/libavcodec/vaapi_encode_mpeg2.c:545
```

Exactly same use-case works HW accelerated when done:
* through FFmpeg QSV API
* using MediaSDK sample transcode application

Looking at the FFmpeg source code, it seems to accept only VA_RC_CQP mode: https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/vaapi_encode_mpeg2.c#L523

And mode is something set before FFmpeg vaapi_encode_mpeg2_configure() is called, as it's not set in ff_cbs_init(): https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/cbs.c#L74

**Comment by eero-t** [comment]
Created upstream ticket: https://trac.ffmpeg.org/ticket/7650

**Comment by uartie** [comment]
@XinfengZhang this looks related to media-driver, not libva directly.  Can you transfer this to that project instead (NOTE: "Transfer issue (Beta)" link on sidebar).  I don't have admin rights to media-driver project to do it.

**Comment by eero-t** [comment]
> Created upstream ticket: https://trac.ffmpeg.org/ticket/7650

That was fixed long time ago (2019), so closing this one too.
