### ISSUE TITLE
Add a new RGB10 FourCC definition instead of 8bit RGB + RTFormat

### ISSUE THREAD

**Issue by zhoujd** [intel/libva#263]
RGB10 surface (R10G10B10A2) defined by both VA_FOURCC_RGBA and VA_RT_FORMAT_RGB32_10 are used. Can you define a new  RGB10 FourCC for easy understand and use RGB10 surface ?

**Comment by XinfengZhang** [comment]
yes, will add it. thanks

**Comment by FurongZhang** [comment]
Will do that ww08.

**Comment by xhaihao** [comment]
This should be done by https://github.com/intel/libva/pull/201

**Comment by zhoujd** [comment]
I am closing it.
