### ISSUE TITLE
add defines for colour_primaries & transfer_characteristics in VAProcColorProperties

### ISSUE THREAD

**Issue by zhoujd** [intel/libva#264]
currently no defines for the values of colour_primaries & transfer_characteristics in VAProcColorProperties (https://github.com/intel/libva/blob/master/va/va_vpp.h#L688-L697).  only "ISO/IEC 23001-8 or ITU H.273" in the comments.

Will you add them ?

**Comment by XinfengZhang** [comment]
are there usagecase ? which filter or vpp feature need it?

**Comment by zhoujd** [comment]
HDR10 tone mapping will use them.

**Comment by FurongZhang** [comment]
@XinfengZhang @zhoujd  I am working on that.

**Comment by FurongZhang** [comment]
Please review this PR https://github.com/intel/libva/pull/315

**Comment by FurongZhang** [comment]
If you think the PR is good, can you please close this issue? @zhoujd.

**Comment by zhoujd** [comment]
It upstreamed, I am closing this issue.
