### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by okias** [intel/libva#270]
Please release 2.4.0 or 2.5.0 (including tarball), since released libva-intel-driver depends on >= 2.4.0 (API 1.4.0)

Thank you

EDIT: my bad, latest commit require this change, which I backported and didn't noticed version bump, but please, release anyway :)

**Comment by XinfengZhang** [comment]
sure, thanks

**Comment by XinfengZhang** [comment]
https://github.com/intel/libva/releases/tag/2.4.0
