### ISSUE TITLE
Any examples? I dont see any included and I'm interested in experimenting

### ISSUE THREAD

**Issue by wade-welles** [intel/libva#286]
I'm interested in working with specifically the wayland components of libva but I can't find any examples in the source code. Are there any examples in other repositories that are not obviously linked in the `README.md`?

Any assistance would be really appreciated, sorry if the is a repeat or I'm missing something very obvious.

**Comment by wade-welles** [comment]
I'm interested in wayland but I would be happy with any examples just to get started, once I had something to start from Id feel much more comfortable making edits to the library and exploring. Just not sure where to start, its a bit overwhelming

**Comment by XinfengZhang** [comment]
application sample or driver sample ? if you want to check driver implementation , you can refer https://github.com/intel/intel-vaapi-driver/blob/master/src/i965_output_wayland.c

**Comment by uartie** [comment]
intel/libva-utils has some wayland display backend examples too.
