### ISSUE TITLE
libva info: va_openDriver() 

### ISSUE THREAD

**Issue by nopaospite** [intel/libva#287]
libva: 1.7.0
system:
Linux hisome-16 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
    what's wrong?when i run the vainfio,print a error message:
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/iHD_drv_video.so
libva error: dlopen of /usr/lib/iHD_drv_video.so failed: /usr/lib/iHD_drv_video.so: undefined symbol: drm_intel_gem_bo_unmap_wc
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

**Comment by XinfengZhang** [comment]
@nopaospite , iHD should use libva 2.x.x
