### ISSUE TITLE
Tag 2.4.1 is not visible

### ISSUE THREAD

**Issue by ceyusa** [intel/libva#296]
Recently the tag 2.4.1 was pushed, but the branch v2.4-branch was not updated. I guess this explains why the tag is not visible in the tag list in github's project page, and in order to fetch the tag it is required to run `git fetch --tags orgin`.

**Comment by XinfengZhang** [comment]
updated v2.4-branch

**Comment by mbakke** [comment]
@XinfengZhang can you also upload a release tarball for 2.4.1 so that `./configure && make` works out of the box?

**Comment by XinfengZhang** [comment]
sure, will add it soon

**Comment by uartie** [comment]
@XinfengZhang is this fixed?

**Comment by XinfengZhang** [comment]
yes, already uploaded the package
