### ISSUE TITLE
Copy Surface Between Different  VA Context

### ISSUE THREAD

**Issue by zhoub** [intel/libva#299]
Hi !

Is that possible to copy the buffer/surface among different VA context ? Thanks !

**Comment by XinfengZhang** [comment]
hi @zhoub , the question is not clear, we always can copy surface between different va context, with several methods:1. map & copy 2. gpu copy .... even has method to shar surfaces. but I suppose you want to access a surface which is created in another va context? 
you can : 1. different VA context with same display handle. 
or get the fd from KMD

**Comment by zhoub** [comment]
@XinfengZhang 
Hi !
Thanks for the reply.

Yes, the program might have several displays, and each display might associate with multiple contexts for video decoding and encoding, and eventually the decoded image would be transferred to GLX. Now the FFmpeg VAAPI has created the VADisplay(), and also program uses the VADisplay from vaGetDisplayGLX().

What I don't understand is that if these 2 displays are the same or it's able to interop the decoded VASurface to the GLX system.

Thank you very much.

**Comment by XinfengZhang** [comment]
@zhoub , you should try to get the fd by vaExportSurfaceHandle from one VAContext, then call vaCreateSurface with the fd in external buffer descriptor for another VAContext.

**Comment by zhoub** [comment]
Finally I tried to use the singleton VADisplay, thanks for the help, close this issue.
