### ISSUE TITLE
[Enhancement]add configuration attribute query for max frame size

### ISSUE THREAD

**Issue by fulinjie** [intel/libva#303]
As the request for enabling max frame size for ffmpeg-vaapi, a query for the support of driver is need. 
Otherwise the feature can only be enabled by hard code, and won't be accept by community easily.

https://patchwork.ffmpeg.org/patch/12932/

**Comment by XinfengZhang** [comment]
add one VAConfigAttribMaxFrameSize? and only enable /disable for the value of this attributes.

**Comment by fulinjie** [comment]
It will be more acceptable to query the support for driver.
If the result is unsupported, max frame size option could be ignored and won't break the entire pipeline for encode.
IMHO, it makes sense.
