### ISSUE TITLE
What happens if program doesn't call VaTerminate() but just terminated.

### ISSUE THREAD

**Issue by zhoub** [intel/libva#310]
Hi

I got some strange behaviour after start-end the program repeatedly when working, after some times the decoding becomes extremely slow. So I was working will the system leaks resources if the program didn't call **vaTerminate()** before quitting ?

Thank you very much !

**Comment by XinfengZhang** [comment]
hi @zhoub ,  of course , some resource (depend on driver implementation) is not released.  such as: GPU memory ...

**Comment by zhoub** [comment]
Understood, thank you very much !
