### ISSUE TITLE
using libva with chromium Surface to pixmap error 

### ISSUE THREAD

**Issue by ajaykamath1986** [intel/libva#325]
I am installing the latest libva driver with chromium on ubuntu 18.04 and using i965 driver on a cofeelake machine.Keep getting the error "failed putting surface to pixmap **vaerror : the requested function is not implemented**" 
this happens on invocation of vaputsurface function call.
![chromedep](https://user-images.githubusercontent.com/11920309/62561931-ce2de000-b89d-11e9-8661-a73df6ddd121.png)
![libva1](https://user-images.githubusercontent.com/11920309/62561932-cec67680-b89d-11e9-9624-59c28b7cc2d8.png)

**Comment by XinfengZhang** [comment]
@ajaykamath1986 , it seems a driver issue, could you help to file a issue on https://github.com/intel/intel-vaapi-driver

**Comment by ajaykamath1986** [comment]
Issue moved to https://github.com/intel/intel-vaapi-driver/issues/481
Thank you
