### ISSUE TITLE
Broken hardware acceleration on Intel I7-1065G7

### ISSUE THREAD

**Issue by s2hsieh** [intel/libva#359]
Not positive where in the chain it is broken, but here it goes.

The problem manifest when playing any video that should be supported by VA-API for direct decoding. This example is using mpv player but it's the  same with other players.

>  (+) Video --vid=1 (*) (h264 1920x1080 30.092fps)
>  (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
> [vaapi] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
> AO: [pulse] 44100Hz stereo 2ch float
> VO: [gpu] 1920x1080 yuv420p
> AV: 00:00:07 / 00:00:08 (99%) A-V:  0.000
> 
> 
> Exiting... (End of file)

I'm running Xubuntu on a Yoga C940. I'm aware that this is a fairly new machine, so any logs that I can provide, I will be happy to do so.

**Comment by s2hsieh** [comment]
It turns out Xubuntu did not have the correct driver installed. it had i965-va-driver instead of intel-media-va-driver.

**Comment by XinfengZhang** [comment]
it should be related with #355 , will merge the fix ASAP

**Comment by uartie** [comment]
@s2hsieh did installing intel-media-va-driver fix this for you?  The i965-va-driver only supports up to CFL (9th generation).  Also see #392.

**Comment by s2hsieh** [comment]
Yes it did. I also updated mesa, since starting in 19.3, IceLake support was greatly improved.
