### ISSUE TITLE
X11 PutSurface dependency issue

### ISSUE THREAD

**Issue by aaronovz1** [intel/libva#361]
https://github.com/intel/libva/blob/7eec6f8ffb399ac33d545b0368079c29ebe6af24/va/va.c#L550

I believe this line should be dependent on whether X11 is available or enabled. I just went through the process of removing X11 dependencies in favor of DRM for MediaSDK and media-driver (iHD) and was getting failures because `vaPutSurface` did not exist in the vtable for iHD driver.

**Comment by XinfengZhang** [comment]
when there are no X11, vaPutsurface will not work in iHD driver

**Comment by aaronovz1** [comment]
I am not sure what you mean. vaPutSurface seems to only be an X11 dependency. It should not be required on systems without X11 and that are using DRM.

I think the following is needed (and is what I've tested locally to make things work):
```
#ifdef HAVE_VA_X11
CHECK_VTABLE(vaStatus, ctx, PutSurface);
#endif
```
Otherwise when X11 is disabled in libva and in [media-driver](https://github.com/intel/media-driver) then we see an error such as:
`No valid vtable entry for vaPutSurface` when initializing the driver/libva.

**Comment by XinfengZhang** [comment]
sorry, made a mistake, yes, we should add some check, not return failed when there are no vaPutSurface implementation .
