### ISSUE TITLE
Checking that per-macroblock QP control supported by underlying driver

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [intel/libva#391]
For CQP rate control, there is a possibility to have per-macroblock QP control (so-called MBQP). Some encoders support MBQP, some not. How is it possible to ask via libva is it supported?

**Comment by dmitryermilov** [comment]
@XinfengZhang , can you please help?

**Comment by XinfengZhang** [comment]
two attribute related with it: VAConfigAttribEncMacroblockInfo VAConfigAttribQPBlockSize, suggest use the second and check the value.

**Comment by dmitryermilov** [comment]
Yes, the 2nd one seems is what we need. Thanks. @Alexandr-Konovalov , could you try?

**Comment by Alexandr-Konovalov** [comment]
@XinfengZhang, I would like to clarify.

I see that VAConfigAttribQPBlockSize is not used in Intel Media Driver, and Intel MediaSDK uses another way to set VAEncQPBuffer size. Should I set VAConfigAttribQPBlockSize’s attribute value to some non-zero value inside Intel Media Driver to mark that MBQP is supported, and zero to mark that there is no MBQP?

**Comment by dmitryermilov** [comment]
> I see that VAConfigAttribQPBlockSize is not used in Intel Media Driver

It's a subject for another issue against media-driver project.

**Comment by XinfengZhang** [comment]
yes, media driver should has related implementation , @Alexandr-Konovalov  thanks, will you add it?

**Comment by Alexandr-Konovalov** [comment]
Yes, sure. Thank you for the information. I think we may want to close the issue.
