### ISSUE TITLE
vaInitialize failed with error code -1 (unknown libva error),exit

### ISSUE THREAD

**Issue by ziyaointl** [intel/libva#392]
I am running Ubuntu 18.04 LTS on i7-10710u. I am trying to get hardware acceleration for x264 working but I have the following error:
```bash
$ vainfo
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```
```bash
$ ls /usr/lib/x86_64-linux-gnu/dri/
i915_dri.so           nouveau_vieux_dri.so  radeonsi_drv_video.so
i965_dri.so           r200_dri.so           swrast_dri.so
i965_drv_video.so     r300_dri.so           virtio_gpu_dri.so
iris_dri.so           r600_dri.so           vmwgfx_dri.so
kms_swrast_dri.so     r600_drv_video.so     zink_dri.so
nouveau_dri.so        radeon_dri.so
nouveau_drv_video.so  radeonsi_dri.so
```
Apologies for the sparse info in this issue because I am not sure what info I should provide. Please feel free to ask for more.

**Comment by uartie** [comment]
The [i965 driver](https://github.com/intel/intel-vaapi-driver/blob/master/README) (i965_drv_video.so) does not support 10th generation Comet Lake (CML).  You will need to use the [iHD driver](https://github.com/intel/media-driver)

**Comment by uartie** [comment]
Also, on Ubuntu 18.04 (bionic) you will need to compile iHD yourself since it is not provided in a distro package until [Ubuntu 19.04 (disco)](https://packages.ubuntu.com/search?arch=any&mode=filename&searchon=names&keywords=intel-media-va-driver) or later, afaik.

**Comment by ziyaointl** [comment]
I compiled the iHD driver and it worked! Thank you very much!
