### ISSUE TITLE
[enhance] Adding timeout for vaSyncSurface

### ISSUE THREAD

**Issue by dmitry-gurulev** [intel/libva#397]
Current ```vaSyncSurface``` interface pushes application to use a separate thread for synchronization, since app. can't afford to block main thread for unknown time.

My suggestion is to a new function add a ```vaSyncSurface2``` w/ ```timeout``` parameter -
```C
VAStatus vaSyncSurface2(
    VADisplay dpy,
    VASurfaceID render_target
    unsigned int timeout
);
```
Either ```VA_STATUS_ERROR_SURFACE_BUSY```\ ```VA_STATUS_ERROR_HW_BUSY``` statuses could be re-used to indicate the timeout is expired or a new one status ```VA_STATUS_ERROR_TIMEOUT``` could be introduced.

**Comment by XinfengZhang** [comment]
hi Dmitry, could you help to file a PR about it?

**Comment by dmitry-gurulev** [comment]
@XinfengZhang,

A new question arose during discussion - how we will sync. at 1->N encode scenario? Looks like we need provide a context to the ```vaSyncSurface2``` or introduce a new one dedicated function - ```vaSyncBuffer``` to sync on bitstream buffer rather than on input surface.

We need a sync to clarify and discuss options and then I file a PR.
