### ISSUE TITLE
Deprecate tg_start and tg_end in VASliceParameterBufferAV1

### ISSUE THREAD

**Issue by rosetta-jpn** [intel/libva#431]
VASliceParameterBufferAV1 is a structure for a single Tile.
tg_start and tg_end are unnecessary but just confusing.
They should be deprecated.

**Comment by XinfengZhang** [comment]
thanks, @rosetta-jpn , different HW vendor maybe has different implementation, not sure about whether it should be deprecated now, lets wait feedback from different channel.

**Comment by rosetta-jpn** [comment]
It was done in https://github.com/intel/libva/commit/1d807f7a77c3b517e1674d8ff201ade93a931a3d.
