### ISSUE TITLE
chroma_sample_position in VADecPictureParameterBufferAV1 should be two bit

### ISSUE THREAD

**Issue by rosetta-jpn** [intel/libva#445]
chroma_sample_position is allocated 1 bit in VADecPictureParameterBufferAV1.
The spec 6.4.2 states the value can be 0, 1 and 2.
An application cannot assign the parsed value as is.
Should the bits of chroma_sample_position be two, or does the application have to do some processing in the assignment?

**Comment by XinfengZhang** [comment]
@zefuli could you help to check whether the bit is enough to represent chroma_sample_position?

**Comment by rosetta-jpn** [comment]
gentle ping!

**Comment by sreerenjb** [comment]
Hm, this needs to be fixed ASAP :(

**Comment by cwang105** [comment]
The parameter should be removed. It is not needed for AV1 decoding.

**Comment by sreerenjb** [comment]
Okay, so we just deprecate the field?

**Comment by rosetta-jpn** [comment]
Thanks. I created a pull request. https://github.com/intel/libva/pull/450
