### ISSUE TITLE
TravisCI status is no longer visibile

### ISSUE THREAD

**Issue by jbeich** [intel/libva#459]
Looking at new commits and pull requests only Intel's buildbot status appears to be visible. #363 adds a new platform to TravisCI config, so it'd be nice if contributors could see if there's any bustage. Can you re-install Travis via [marketplace](https://github.com/marketplace/travis-ci)?

See also https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798

**Comment by dvrogozh** [comment]
I am not sure when libva lost travis ci status on commits. But it seems there is pretty big delays when travis ci is actually triggers. Not sure we can fix this delay.... Let me ask this question: does anyone has objections if we will explore Github Actions (instead of Travis CI) to perform CI checks?

**Comment by jbeich** [comment]
> explore Github Actions (instead of Travis CI)

- Github Actions is [not supported on FreeBSD yet](https://github.com/actions/runner/issues/385).
- TravisCI [supports](https://github.com/travis-ci/travis-build/pulls?q=is%3Apr+freebsd+is%3Aclosed) FreeBSD but not documented yet. I've tested it in a dozen of projects.

See also https://wiki.freebsd.org/HostedCI

**Comment by dvrogozh** [comment]
freebsd is not supported directly, but there is a way thru virtual machine on macos (macos is supported). See: https://github.com/vmactions/freebsd-vm. I tried it today - seems working. We can use this path. Or you see some issues with it?

**Comment by jbeich** [comment]
How fast is VM approach? For libva it may not matter but media-driver takes ~15 minutes on TravisCI even with ccache enabled.

**Comment by jbeich** [comment]
Err, ccache isn't used on FreeBSD in media-driver for some reason (preprocessor error). It works fine in other repos.
https://travis-ci.org/github/intel/media-driver/builds/732136089

**Comment by dvrogozh** [comment]
I don't know - this needs to be tried. But github action jobs are being started in dozens of seconds comparing to few hours for travis which is a huge difference. I agree though that this needs to be checked. There is a clock skew issue by the way which I stepped into trying this approach for libva. So I filed https://github.com/vmactions/freebsd-vm/issues/2. Appreciate ideas on how to resolve.

**Comment by dvrogozh** [comment]
Projects has switched to github actions with #485 merged. FreeBSD build is covered: https://github.com/intel/libva/blob/master/.github/workflows/freebsd.yml. I believe concern is no longer valid. Closing the issue.
