### ISSUE TITLE
autotools: --enable-wayland broken when using dash as CONFIG_SHELL

### ISSUE THREAD

**Issue by Polynomial-C** [intel/libva#489]
Since commit 78431a361bed0b6e9f1f3ebc0de8897b069b3848 using autotools with GNU sed to build libva fails when --enable-wayland is set:
```
Making all in wayland
make[3]: Entering directory '/var/tmp/portage/x11-libs/libva-2.10.0/work/libva-2.10.0-abi_x86_64.amd64/va/wayland'
/usr/bin/wayland-scanner client-header < /var/tmp/portage/x11-libs/libva-2.10.0/work/libva-2.10.0/va/wayland/wayland-drm.xml > wayland-drm-client-protocol.h
/usr/bin/wayland-scanner code < /var/tmp/portage/x11-libs/libva-2.10.0/work/libva-2.10.0/va/wayland/wayland-drm.xml > wayland-drm-client-protocol-export.c
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
/bin/sed -e $'1i\\\n#include "sysdeps.h"\n' \
                   -e 's@WL_EXPORT@DLL_HIDDEN@g' < wayland-drm-client-protocol-export.c > wayland-drm-client-protocol.c
/bin/sed: -e expression #1, char 2: unknown command: `1'
make[3]: *** [Makefile:768: wayland-drm-client-protocol.c] Error 1
```

My sed is:
```
# sed --version | head -n1
sed (GNU sed) 4.8
```
Reverting commit 78431a361bed0b6e9f1f3ebc0de8897b069b3848 makes the build succeed.

**Comment by dvrogozh** [comment]
@jbeich : fyi, one more issue after fixes for bsd.

**Comment by jbeich** [comment]
I can't reproduce:
```
$ pkg install gsed
$ gsed --version | head -1
gsed (GNU sed) 4.8

$ ./autogen.sh
$ ./configure
$ gmake V=1 SED=gsed -C va/wayland wayland-drm-client-protocol.c
gmake: Entering directory 'va/wayland'
/usr/local/bin/wayland-scanner code < wayland-drm.xml > wayland-drm-client-protocol-export.c
Using "code" is deprecated - use private-code or public-code.
See the help page for details.
gsed -e $'1i\\\n#include "sysdeps.h"\n' \
                   -e 's@WL_EXPORT@DLL_HIDDEN@g' < wayland-drm-client-protocol-export.c > wayland-drm-client-protocol.c
gmake: Leaving directory 'va/wayland'
```

**Comment by jbeich** [comment]
> /bin/sed: -e expression #1, char 2: unknown command: `1'

`1` is address (line) prefix for `i` (insert) command but GNU sed appears to encounter another character before `1`. Can you debug how your shell expands `$'...'` syntax? I've tried `SHELL=bash` and replacing `/bin/sh` with bash but still couldn't reproduce.

**Comment by thesamesam** [comment]
Can you try CONFIG_SHELL=/bin/sh instead?

**Comment by Polynomial-C** [comment]
That might be the real problem. I have `/bin/sh -> dash`. When I use `CONFIG_SHELL="/bin/bash"` the error is gone. But IMHO this should work independent of what shell is being used.

**Comment by Polynomial-C** [comment]
And it seems to be a problem specific to dash. With `CONFIG_SHELL="/bin/mksh"` the build also succeeds. I have only tested `dash-0.5.11.3` yet though.

**Comment by jbeich** [comment]
dash appears to lack https://github.com/freebsd/freebsd-src/commit/a62ab0274a1a or https://github.com/netbsd/src/commit/5a196a26cf49.
```sh
$ dash
$ echo $'1i'
$1i
```

**Comment by jbeich** [comment]
Nevermind, dash appears to expand C-style escape sequences even outside of `$'...'`.
```sh
$ dash
echo '\053'
+
$ bash
$ echo '\053'
\053
```

**Comment by jbeich** [comment]
Oops, I forgot `echo` also may expand C-style escape sequences.

**Comment by jbeich** [comment]
@Polynomial-C, does https://github.com/intel/libva/pull/490 help?

**Comment by Polynomial-C** [comment]
@jbeich: yes, it does help. No more build issues with `dash`. Also successfully tested with `mksh` and `bash`. Build with `zsh` fails but the error seems to be unrelated to this issue.
