### ISSUE TITLE
v2.11.0 uses a lot more GPU memory when decoding VP9

### ISSUE THREAD

**Issue by tgn-ff** [intel/libva#511]
The issue is not reproducible when decoding h264, but I didn't test anything other than h264 and VP9.

Opening any video, immediately increases the GPU memory usage by at least 0.5GiB. I can reproduce it with mpv, vlc and chromium. Downgrading to v2.10.0 is enough to resolve the issue.

I ran a bisection and ended up to the following result, which I have no idea if it makes sense:

    3b636aa90e6fb10b1b6f853d2649af8963c10377 is the first bad commit
    commit 3b636aa90e6fb10b1b6f853d2649af8963c10377
    Author: Carl Zhang <carl.zhang@intel.com>
    Date:   Fri Dec 11 10:28:54 2020 -0500

        libva 2.11.0.pre1

        Signed-off-by: Carl Zhang <carl.zhang@intel.com>

     configure.ac | 2 +-
     meson.build  | 4 ++--
     2 files changed, 3 insertions(+), 3 deletions(-)

I, also, tried to find out whether the issue is with libva-mesa-driver. The issue still reproduces in 20.2.2, but the video decoding fails completely in previous versions (ie. in 20.2.1 and before), so I can't run a bisection on that side.

My distro is archlinux. The GPU is an AMD RX 5700XT.

**Comment by XinfengZhang** [comment]
it should be media_driver issue, could I move it into media driver repo?
