### ISSUE TITLE
Possibly wrong version in the .pc file?

### ISSUE THREAD

**Issue by rubyFeedback** [intel/libva#512]
Hey guys,

I noticed that a new release for libva may be out soon?

Anyway. I have a slight minor problem with libva-2.10.0, in regards to its libva.pc file.

I did a test-compilation into a custom directory.

The content of libva.pc is:

    prefix=/home/Programs/Libva/2.10.0
    exec_prefix=${prefix}
    libdir=${exec_prefix}/lib
    includedir=${prefix}/include
    driverdir=${exec_prefix}/lib/dri
    libva_version=2.10.0

    Name: libva
    Description: Userspace Video Acceleration (VA) core interface
    Version: 1.10.0
    Libs: -L${libdir} -lva
    Cflags: -I${includedir}

The version shown by libva is 1.10.0.

Should this not be 2.10.0 instead? The second one.

Anyway I am reporting this just in case it was not fixed already; please
disregard when 2.11.0 does not show this error (I think it is an error
because the version does not match the URL at
https://github.com/intel/libva/releases/download/2.10.0/libva-2.10.0.tar.bz2
)

**Comment by XinfengZhang** [comment]
the libva.pc is generated. not in source repo. you could run autogen.sh to generate it.

**Comment by uartie** [comment]
One is the libva library version (libva_version), the other is the VA API version (Version).  They are not the same.

It's possible for multiple [minor] release versions of libva but VA API version may not change.
