### ISSUE TITLE
drm state fd is not closed

### ISSUE THREAD

**Issue by StarsGreen** [intel/libva#535]
as is descriped is just about libva 2.7:
va_DisplayContextGetNumCandidates and va_DisplayContextGetDriverName are called while getDisplay is called using x11 as display.But the key is that va_isDRI2Connected will called in va_DisplayContextGetNumCandidates and va_DisplayContextGetDriverName func and device(such as /dev/dri/card0) fd will be opened in va_isDRI2Connected twice,But finally  the newer fd will be closed in va_DisplayContextDestroy,and the another fd will be ignored. So some terrible issue will occur while stress test is happening and then /dev/dri/card0 will be opened man times and there is no way to close it because older fd is ignored.Maybe there should be some changes about it

**Comment by XinfengZhang** [comment]
it should already been fixed by b4e690fb33cbfb35a12cffe4b655a4045f71aa82

**Comment by StarsGreen** [comment]
got it
