### ISSUE TITLE
crash in libva when using iHD with mpv and vo=vaapi on Xwayland

### ISSUE THREAD

**Issue by LaserEyess** [intel/libva#536]
Most information is copy and pasted from: https://github.com/intel/media-driver/issues/1095.

Essentially, the following command can reproduce a null pointer dereference inside libva when running under wayland
```
LIBVA_DRIVER_NAME=iHD mpv --no-config --vo=vaapi $file
```
`vo=vaapi` is Xorg only, so when you run this command under wayland it uses Xwayland. Quoted from the other issue.

> I  have rebuilt a libva (https://github.com/intel/libva/commit/6e86b4fb4dafa123b1e31821f61da88f10cfbe91) and this repository (https://github.com/intel/media-driver/commit/f315c36020eed2d2b52b9557cb888ca535f17886) and got mpv to work with them via `LD_PRELOAD` and `LIBVA_DRIVERS_PATH`. Both of them have full debug symbols and I can set breakpoints if needed to step through the code.
 >
> Here is a current backtrace: https://0x0.st/-J1l.txt
>
> Jexu's PR fixed an assert the line right before the crash, it calls into [`dri_vtable->get_drawable()`](https://github.com/intel/media-driver/blob/master/media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp#L392) here and crashes.
>
> It looks like what happens is that inside that function is that it immediately calls into a funciton called `do_drawable_hash` in libva. In there it hits [this line](https://github.com/intel/libva/blob/master/va/x11/va_dricommon.c#L74), and the problem there is
> ```
> (gdb) info locals
>
> dri_state = 0x7fab78023100
> index = 2
> dri_drawable = 0x0
> (gdb) p dri_state->createDrawable
> $1 = (struct dri_drawable *(*)(VADriverContextP, XID)) 0x0
> ```
> So that's the issue I guess, a NULL pointer as this function? I did not look any further than this, but it looks like `dri_state` is [created here](https://github.com/intel/libva/blob/master/va/x11/va_dricommon.c#L64).
>
Let me know if I need to provide anything else. This is trivial to reproduce.

**Comment by Jexu** [comment]
@LaserEyess Can you help verify and review the fix?

**Comment by LaserEyess** [comment]
No this did not work. If you look at my previous backtrace `dri_drawable` was also NULL, so you have only delayed the crash by exactly one line. Now it crashes on `dri_drawable->x_drawable = drawable;`.

**Comment by LaserEyess** [comment]
Unsure if this is helpful but here is a crash with `LIBVA_TRACE=1` https://0x0.st/-Jv3.thd-0x0

**Comment by LaserEyess** [comment]
The latest update for #537 does fix the crash but results in some undesirable behavior on mpv's side. I guess that must be fixed by mpv.

**Comment by XinfengZhang** [comment]
hi @LaserEyess , the vaPutSurface is used to copy media surface to X drawable which is get by DRI2,  XWayland should just support DRI3. "xdpyinfo|grep DRI" will list the supported extension.

**Comment by LaserEyess** [comment]
Yes it's only DRI3, I understand this is the issue. As long as the crash is fixed I believe this bug can be closed. Unfortunately mpv has no way of knowing ahead of time whether or not it's running on xwayland or plain X11 so when `vaPutSurface` fails it just tries to keep going. That's not a libva issue, obviously, I just wish there was a way to signal to mpv what the issue is.
