### ISSUE TITLE
Add VAConfigAttribMinPicture(Width|Height)

### ISSUE THREAD

**Issue by rosetta-jpn** [intel/libva#603]
There are [VAConfigAttribMaxPicture(Width|Height)](
https://github.com/intel/libva/blob/395e502d162fe04ccec7700bd1a58dca40328605/va/va.h#L744).
I think we should also have the config attribution about minimum picture width and height.

Can you also clarify the difference of them from VASurfaceAttrib(Max|Min)(Width|Height)?

**Comment by XinfengZhang** [comment]
they are same, actually [VAConfigAttribMaxPicture(Width|Height)](https://github.com/intel/libva/blob/395e502d162fe04ccec7700bd1a58dca40328605/va/va.h#L744). are introduced by a debate, that we could use bigger surface to handle smaller resolution.  but actually, in practice , they are same.

**Comment by rosetta-jpn** [comment]
I got it. Thanks for clarification.
Does it make sense to add VAConfigAttribMinPicture*?

**Comment by XinfengZhang** [comment]
because there are already VASurfaceAttribMinHeight and VASurfaceAttribMinWidth, if we add VAConfigAttribMinPicture, it will add another two duplicate attributes ...

**Comment by rosetta-jpn** [comment]
Fair enough. Let's Close this as Won't Fix.
