### ISSUE TITLE
libva-win32: warnings during compile/link 

### ISSUE THREAD

**Issue by dvrogozh** [intel/libva#645]
See: https://github.com/intel/libva/actions/runs/3298661454
Commit: https://github.com/intel/libva/commit/da4a18fe814c9695f420d466ad3065cebdbe288a

* windows-msvc:
```
LINK : warning LNK4044: unrecognized option '/Wl,-version-script,D:\a\libva\libva\va/libva.syms'; ignored
```

* windows-mingw:
```
../va/va_trace.c:947:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
```

@sivileri : can you, please, help to fix these?

**Comment by sivileri** [comment]
@dvrogozh https://github.com/intel/libva/pull/647 has some changes for these
