### ISSUE TITLE
libva-2.18.0 release?

### ISSUE THREAD

**Issue by rubyFeedback** [intel/libva#704]
Hi,

I read that there is a new libva but it is not on https://github.com/intel/libva/releases/download/2.18.0/libva-2.18.0.tar.bz2 - could it be added?

**Comment by XinfengZhang** [comment]
yes, it will be added soon, 
current release process is: 1. tag 2. test 3. add tarball.

**Comment by XinfengZhang** [comment]
https://github.com/intel/libva/releases/tag/2.18.0
