### ISSUE TITLE
Correct the av1 enc API; byte_offset_frame_hdr_obu_size is necessary

### ISSUE THREAD

**Issue by rosetta-jpn** [intel/libva#723]
The libva states the offset values of VAEncPictureParameterBufferAV1 are ignored in CQP mode. 
However, the produced bitstream is corrupted in fact if they are not filled in CQP mode.  
As far as we talked with media-driver folks, byte_offset_frame_hdr_obu_size needs to be filled even in CQP mode.
Indeed, a driver can read the offset from the packed headers, but it seems to be reasonable for an app to fill it.

So I think it would be better to correct the API; byte_offset_frame_hdr_obu_size needs to be filled regardless bitrate modes.

**Comment by XinfengZhang** [comment]
thanks for reporting， will file PR to fix it ASAP

**Comment by XinfengZhang** [comment]
and there are one WA , which could work before libva fix merged. 
https://github.com/intel/media-driver/pull/1691

**Comment by rosetta-jpn** [comment]
Any update?

**Comment by XinfengZhang** [comment]
#726 was merged, then it could be closed?

**Comment by rosetta-jpn** [comment]
Yes, SGTM.
