### ISSUE TITLE
Question: is Celeron N2830 (with Intel® HD Graphics for Intel Atom® Processor Z3700 Series) supported?

### ISSUE THREAD

**Issue by Talkless** [intel/libva#739]
Sorry for creating non-issue, but is there a reliable way to check if libva supports some specific processor for H264 HW decoding, for example N2830 in this case?

I believe I've had some Atom processor that didn't work quite some time ago, so seeing this Celeron with Atom GPU raises eyebrow..

Thanks!

**Comment by XinfengZhang** [comment]
suppose it works , but need use another driver 
https://github.com/intel/intel-vaapi-driver

**Comment by Talkless** [comment]
I guess it's this Debian pacakage: https://tracker.debian.org/pkg/intel-vaapi-driver-shaders, so I assume it's should be available.

Thanks!
