### ISSUE TITLE
jumps in either the video or the audio when using hardware accelleration for video playback

### ISSUE THREAD

**Issue by calestyo** [intel/libva#742]
Hey.

Shamelessly copying my own bug report at https://gitlab.freedesktop.org/drm/intel/-/issues/9065 from where I was redirected to `libva`.

<hr>

Not sure whether this is actually an issue in ~i915~ `libva`, since there are probably quite a few other libs/etc. that may be involved.<br>
If you have a better clue, please redirect me accordingly.

Let me first describe the issue.

Since quite a while now (> 1 year) the following happens when playing back a video with `mpv` (which I've configured to use hw decoding (`hwdec=auto` in `.config/mpv/mpv.conf`):<br>
When I pause the video an wait a while, e.g. leave fullscreen, go do another workspace, do some work, etc. ... after coming back and resuming playback of the video, either right at the beginning of that (or shortly afterwards, like 10s), there are a series of "jumps" in the video. That is I see that the motion is not fluent anymore and the video resumes at a later point.<br>
The audio is **not** affected but play just smoothly.<br>
The jumps are first longer (may 1 second or perhaps 2 at most... maybe also even a bit smaller than 1 second) and subsequent jumps get shorter and shorter.<br>
In total, there will be around 5-7 jumps or so... from then on playback works just fine (until I repeat the process, pause, wait a while, resume).

Also, with the same hardware, this used to work "previously" (whenever that was exactly, I do not remember), so it must be some sort of regression.<br>
When using software decoding, no such problems occur.

Now first I though it may be an issue in `mpv`, so I wanted to try with another player and used `vlc` for that. Again with hw decoding enabled (`--ffmpeg-hw`).

I do basically the same as above, pause a video, do some other stuff, resume playback.

Here things become interesting:<br>
`vlc` does not suffer from jumps in the video, it seems, instead there are periods where the audio is either silent or distorted. Again, it happens a few times (not really sure whether the periods get shorter, as the jumps in the video with `mpv` seem to do) and then it's resolved and playback continues just fine.

Even more interesting, if I have a video in both, `mpv` and `vlc`, at pause (for a while) and resume in one of the two... and wait until the issue resolves there... if then ("right afterwards") I resume in the other, the issue doesn't seem to occur in that.

Some versions (ask if you need any other data):
- running Debian unstable
- kernel 6.4.4
- Xorg / Cinnamon
- mpv 0.36.0
- vlc 3.0.13-8-g41878ff4f2
- MESA 23.1.4
- libva2 2.19.0
- i965-va-driver 2.4.1
- intel-media-va-driver 23.2.3
- GPU is integrated in the 12th Gen Intel(R) Core(TM) i7-1270P

```
$ vainfo 
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.19 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```

Any ideas?

Thanks,<br>
Chris.

**Comment by XinfengZhang** [comment]
sorry for late response, but TBH, it should be a MPV or VLC issue, libva just decode bitstreams and share it with display. no DTS/PTS ... any kind of timestamp or any kind of audio/video sync. 
one dumb question? when the video or audio jump. how about the scroll bar/progress bar? also jump or not

**Comment by calestyo** [comment]
Hmm, it seems that some update has fixed this recently (after the issue existed for probably a year or rather even longer.

And since there wasn't any `mpv` update recently, I'd say hat the bug was in fact in some graphics library (no idea, though, which).

Anyway, closing this therefore.

Thanks,
Chris.
