### ISSUE TITLE
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### ISSUE THREAD

**Issue by MichaelJCole** [intel/libva#772]
Hi, I'm building an electron app, which has a build of chromium.  I'm working on Linux Mint 21.2 and getting the above error.  

Linux Mint includes the popular Cinnamon desktop, uses flatpack to install the nvidia drivers.

It may be related to https://github.com/KhronosGroup/Vulkan-Loader/issues/1369

To Reproduce:
0.  Start linux mint
1.  clone this repo: https://github.com/MichaelJCole/nuxt-programmatic-usage-quasar
2.  npm install
3.  npm run dev
4.  Look in the console
5.  You'll see this line very early: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
6.  Some vulkan-loader warnings show in a minute or two

If I run vainfo, I don't get much.

```
> $ vainfo
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
                                                                                                                                                                             
> $ LIBVA_DRIVER_NAME=nvidia vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'nvidia'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

I also ran this:

```
> $ LIBVA_TRACE=true npm run start

> electron@1.0.0 start
> electron .

libva info: Open new log file true.201743.thd-0x00004fa9 for the thread 0x00004fa9
libva info: LIBVA_TRACE is on, save log into true.201743.thd-0x00004fa9
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

> $ cat true.201743.thd-0x00004fa9
[33895.462307][ctx       none]==========va_TraceInitialize
[33895.462310][ctx       none]=========vaInitialize ret = VA_STATUS_ERROR_UNKNOWN, unknown libva error 
[33895.462312][ctx       none]==========va_TraceTerminate
[33895.462325][ctx       none]=========vaTerminate ret = VA_STATUS_SUCCESS, success (no error) 
```

The directory is there, but the driver isn't:
```
> $ ls /usr/lib/x86_64-linux-gnu/dri/     
crocus_dri.so            i965_drv_video.so        nouveau_dri.so           r600_drv_video.so        virtio_gpu_dri.so                               
d3d12_dri.so             iHD_drv_video.so         nouveau_drv_video.so     radeonsi_dri.so          virtio_gpu_drv_video.so                         
d3d12_drv_video.so       iris_dri.so              r300_dri.so              radeonsi_drv_video.so    vmwgfx_dri.so                                   
i915_dri.so              kms_swrast_dri.so        r600_dri.so              swrast_dri.so            zink_dri.so          
```

What should I do to clear the error and use libva in electron?

**Comment by mirh** [comment]
Putting aside that you are using a 3 years old version (last one is 1.20), the vaapi driver isn't part of any nvidia package. 
`vdpau-va-driver` is what you are looking for.

**Comment by MichaelJCole** [comment]
Hi @mirh , thanks for your comment.  I'm not sure what to do with it though.

I'm using Mint which kind of sucks for nvidia drivers.

Is this an upstream issue with Electron or with Mint

Thank you!

**Comment by mirh** [comment]
It's the driver being old, unmaintained and unpatched by the distro
You are going to see that error in every application that tries to use it

**Comment by MichaelJCole** [comment]
Ok, thanks.  I tried the distro forums and they were unhappily unhelpful. 

I'll probably switch distros soon for another reason.

Thanks for the help!
