### ISSUE TITLE
Cannot find tarball release signing key

### ISSUE THREAD

**Issue by 0strodamus** [intel/libva#805]
I cannot find public key 0x8B99990502A81421 that is being used to sign the tarball releases.
I get no results from http://keys.openpgp.org/, http://pgp.mit.edu, and https://keyserver.ubuntu.com.
I have also searched this project and get no results.
Can someone please let me know where the signing key is located and possibly add this information to the readme.md?
The libva-utils repository has the same issue.
Thanks!

**Comment by XinfengZhang** [comment]
thanks, will update the public key for the release tar ball

**Comment by XinfengZhang** [comment]
https://keys.openpgp.org/search?q=421E5C3C1148E3DB9372378E8B99990502A81421

**Comment by 0strodamus** [comment]
Thank you!
